blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://t.me/nhankyjangchan
    about: Please ask and answer questions here.
  - name: 🔒 Security Policy
    url: https://github.com/nhankyjangchan/koajs-cors/security/policy
    about: Please report security vulnerabilities here.
